In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
import pandas as pd
df = pd.read_csv(r"D:\ai_samp_class\House price prediction.csv")
df.head(2)

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.0,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.0,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0


In [5]:
df.shape

(7120, 108)

In [6]:
df.size

768960

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7120 entries, 0 to 7119
Columns: 108 entries, bath to location_Tumkur Road
dtypes: float64(5), int64(103)
memory usage: 5.9 MB


In [8]:
df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [9]:
du=df.duplicated().sum()
print("print duplicate rows",du)

print duplicate rows 467


In [10]:
# price is the target variable
x=df.drop('price',axis=1)
y=df['price']

In [11]:
print("shape of x",x.shape)
print("shape of y",y.shape)

shape of x (7120, 107)
shape of y (7120,)


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train ,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=200)

In [14]:
print("shape of x_train",x_train.shape)
print("shape of x_test",x_test.shape)

shape of x_train (5696, 107)
shape of x_test (1424, 107)


In [15]:
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

shape of y_train (5696,)
shape of y_test (1424,)


In [16]:
# FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit(x_train)
x_train=sc.transform(x_train)
x_test=sc.transform(x_test)
# we apply scaling on input data only

In [17]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [18]:
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [19]:
#PREDECTION OF TEST AND TRAINING SET RESULT
y_pred=lr.predict(x_train)

In [20]:
lr.coef_

array([ 1.11112089e+00, -3.37902113e-01,  7.53102323e+01, -1.47557637e+01,
        6.19412678e+01,  1.95121482e-01, -1.28963697e+00, -3.20545388e+00,
       -1.82919196e+00, -3.92959292e+00, -2.54604992e+00,  2.69379751e-01,
       -1.22809367e+00,  1.72520090e+00,  2.20215535e-01, -1.56872281e+00,
       -5.05773658e-01,  2.22679897e+00, -1.78522509e+00,  2.37030317e+00,
       -3.02550814e+00, -1.76024366e+00, -1.03323030e+00, -2.73763240e-01,
        9.78951200e-01,  1.43315773e+00, -5.07149660e+00, -8.57092460e-01,
       -6.08516847e-01,  1.33082901e+00, -6.65318022e-01, -2.26439056e-01,
        3.56227701e-01, -1.56067658e+00, -1.03530585e-01, -1.47457346e+00,
        4.21230578e-01,  5.75126649e-01,  3.41542251e+00,  4.66266786e-03,
        2.91307034e-01,  2.44703813e-01, -4.48672534e-01,  8.09637593e-01,
       -1.52910960e+00, -3.01297867e+00, -4.52242329e-01, -6.15348810e-02,
       -7.92538150e-01, -3.58448165e+00, -1.03424680e+00,  2.32660137e-01,
        9.23067702e-01, -

In [21]:
# intercept
lr.intercept_

np.float64(95.56461025280898)

In [22]:
# score
lr.score(x_test,y_test)

0.8287379764174043

In [23]:
x_test

array([[-0.44085427, -0.74629288, -0.70162942, ..., -0.05307449,
        -0.05785186, -0.05138463],
       [-0.44085427, -0.74629288, -0.61321779, ..., -0.05307449,
        -0.05785186, -0.05138463],
       [-0.44085427,  0.55204999, -0.55109071, ..., -0.05307449,
        -0.05785186, -0.05138463],
       ...,
       [-0.44085427, -2.04463575, -0.62158105, ..., -0.05307449,
        -0.05785186, -0.05138463],
       [ 0.69231627,  0.55204999,  0.75238338, ..., -0.05307449,
        -0.05785186, -0.05138463],
       [ 0.69231627,  0.55204999,  0.28045646, ..., -0.05307449,
        -0.05785186, -0.05138463]], shape=(1424, 107))

In [24]:
lr.predict([x_test[0,:]])

array([17.46265434])

In [25]:
y_test

3726     39.0
3889     55.0
2469     56.0
4439    154.0
3639     70.0
        ...  
5471     68.0
2358    125.0
542      30.0
4369    150.0
6957     95.0
Name: price, Length: 1424, dtype: float64

In [26]:
lr.predict([x_test[1,:]])

array([56.37945539])

In [27]:
lr.predict([x_test[2,:]])

array([55.91438207])

In [28]:
lr.predict([x_test[3,:]])

array([166.54071137])

In [29]:
# here we are using slicing for predicting data 


In [30]:
from sklearn.metrics import mean_absolute_error , mean_squared_error,r2_score

In [31]:
y_pred=lr.predict(x_test)
y_pred

array([ 17.46265434,  56.37945539,  55.91438207, ..., -10.39195448,
       152.23872159,  93.54686216], shape=(1424,))

In [32]:
# MAE
print("MAE Value:",mean_absolute_error(y_test,y_pred))

MAE Value: 18.290047611465795


In [33]:
#MSE
print("MSE Value:",mean_squared_error(y_test,y_pred))

MSE Value: 3427.5923177288582


In [34]:
# RMSE
print("RSME Value:",np.sqrt(mean_squared_error(y_test,y_pred)))

RSME Value: 58.54564302942499


In [35]:
from sklearn.metrics import r2_score

In [38]:
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.8287379764174043
